version: '3.8'

services:
  postgres:
    image: postgres:18.3
    container_name: cardapio-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./src/banco.sql:/docker-entrypoint-initdb.d/init.sql